version: '3.9'

services:
  web-app:
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - ./src:/src
    command: >
      sh -c "./manage.py collectstatic --noinput && gunicorn -b 0.0.0.0:8000 config.wsgi:application"
    env_file:
      - .env.docker

  db:
    image: postgres:15
    restart: always
    env_file:
      - .env.docker
    ports:
      - "5435:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    restart: unless-stopped
    image: redis:7.2.4
    container_name: redis
    ports:
      - "6379:6379"

  worker:
    build:
      context: .
    hostname: celery
    entrypoint: celery
    command: -A celery_app.app worker --loglevel=info
    volumes:
      - ./src:/src
    env_file:
      - .env
    depends_on:
      - redis
    links:
      - redis

  flower:
    build:
      context: .
    hostname: flower
    entrypoint: celery
    command: -A celery_app.app flower --loglevel=info
    volumes:
      - ./src:/src
    env_file:
      - .env
    depends_on:
      - redis
    links:
      - redis
    ports:
      - "5555:5555"


volumes:
  postgres_data:
